int(){

cin>>long;
vector(),t(+1),rest(+1);
vector();
vector();
for(long=1;long<=;long++){
cin>>vector[long];
}
for(long=1;long<=;long++){
cin>>t[long];
vector[long]=t[long]+vector[long-1];
}
for(long=1;long<=;long++){
long=long-1;long=n+1;
while(long<long){
long=(long+long)/2;
if(vector[long]-vector[long-1]<vector[long]){
long=long+1;
}else{
long=long;
}
}
rest[long]=vector[long]-vector[long-1]+vector[long-1];
vector[long].push_back(long);
}
long=vector[0].size(());
for(long=1;long<=;long++){
long=0;
long+=vector[long].size();
long+=t[long]*(long-long);
for(long=0;long<vector[long].size();long++){
long+=rest[vector[long][long]];
}
cout<<long<<' ';
}
cout<<endl;
}
42

